import Link from "next/link";
import { LeadConfig } from "@/lib/types";
import { Button } from "../ui/Button"; // standard relative import
import { logServerEvent } from "@/lib/analytics";

interface BaseShellProps {
  children: React.ReactNode;
  lead?: LeadConfig | null;
  industry?: string;
  slug?: string;
  ctaLink?: string; // e.g. Payment Link or /pricing
}

export function BaseShell({ children, lead, industry, slug, ctaLink }: BaseShellProps) {
  
  return (
    <div className="flex min-h-screen flex-col">
      {/* Top Banner */}
      <div className="bg-primary text-primary-foreground text-center py-2 text-sm font-medium">
        Preview Mode — This is a demo site generated by Teklytic. 
        <Link href="https://teklytic.com" className="ml-2 underline underline-offset-2">
          Launch yours in 48 hours &rarr;
        </Link>
      </div>

      {/* Header */}
      <header className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container flex h-16 max-w-screen-2xl items-center justify-between">
          <div className="flex items-center gap-4">
             {/* Logo */}
             <Link href="/" className="font-bold text-xl tracking-tight">
                {lead?.businessName || "Your Business Name"}
             </Link>
          </div>
          
          <nav className="hidden md:flex items-center gap-6 text-sm font-medium">
             {industry && slug ? (
                 <>
                   <Link href={`/${industry}/${slug}`} className="transition-colors hover:text-foreground/80 text-foreground/60">Home</Link>
                   <Link href={`/${industry}/${slug}/services`} className="transition-colors hover:text-foreground/80 text-foreground/60">Services</Link>
                   <Link href={`/${industry}/${slug}/blog`} className="transition-colors hover:text-foreground/80 text-foreground/60">Blog</Link>
                 </>
             ) : (
                <span className="text-muted-foreground">Demo Navigation</span>
             )}
          </nav>

          <div className="flex items-center gap-2">
            {ctaLink && (
                 <Link href={ctaLink} target="_blank" rel="noopener noreferrer">
                    <Button 
                       size="sm" 
                       className="hidden sm:inline-flex"
                    >
                      Launch This Site
                    </Button>
                 </Link>
            )}
            
            {!ctaLink && (
                <Link href="https://teklytic.com">
                   <Button size="sm" variant="outline">Get Started</Button>
                </Link>
            )}
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1">
        {children}
      </main>

      {/* Footer */}
      <footer className="border-t py-6 md:py-0">
         <div className="container flex flex-col items-center justify-between gap-4 md:h-24 md:flex-row">
            <p className="text-center text-sm leading-loose text-muted-foreground md:text-left">
               © {new Date().getFullYear()} {lead?.businessName || "Demo Business"}. All rights reserved.
            </p>
            <p className="text-center text-sm text-muted-foreground">
               Powered by <Link href="https://teklytic.com" className="font-medium underline underline-offset-4">Teklytic</Link>
            </p>
         </div>
      </footer>
    </div>
  );
}
